from collections import deque

from sample_factory.algo.utils.misc import LEARNER_ENV_STEPS, TRAIN_STATS

# IntrMotiv metrics are deliberately kept outside Sample Factory's generic
# train/ namespace. The callback removes these keys before the built-in
# handler runs, leaving train/ for PPO and framework diagnostics only.
INTRMOTIV_SUMMARY_TAGS = {
    "memory_onset": "intrmotiv/memory/onset_fraction",
    "memory_novel_onset": "intrmotiv/memory/novel_onset_fraction",
    "memory_familiar_onset": "intrmotiv/memory/familiar_onset_fraction",
    "memory_gate_violation": "intrmotiv/memory/gate_violation_fraction",
    "memory_goal_ambiguous": "intrmotiv/memory/goal_ambiguous_fraction",
    "memory_goal_active": "intrmotiv/memory/goal_active_fraction",
    "memory_goal_hit": "intrmotiv/memory/goal_hit_fraction",
    "memory_replay_mismatch": "intrmotiv/memory/replay_mismatch",
    "distance_metric": "intrmotiv/distance/mean",
    "distance_metric_max": "intrmotiv/distance/max",
    "distance_metric_min": "intrmotiv/distance/min",
    "distance_metric_std": "intrmotiv/distance/std",
    "distance_metric_masked": "intrmotiv/distance/masked_mean",
    "distance_metric_masked_max": "intrmotiv/distance/masked_max",
    "distance_metric_masked_min": "intrmotiv/distance/masked_min",
    "distance_metric_masked_std": "intrmotiv/distance/masked_std",
    "activated_sequences": "intrmotiv/dg/active_count",
    "activated_sequences_max": "intrmotiv/dg/active_count_max",
    "activated_sequences_min": "intrmotiv/dg/active_count_min",
    "activated_sequences_std": "intrmotiv/dg/active_count_std",
    "iterative_phase": "intrmotiv/update/phase",
    "encoder_loss": "intrmotiv/encoder/loss",
    "decoder_loss": "intrmotiv/decoder/loss",
    "reward_for_advantage_mean": "intrmotiv/reward/advantage_mean",
    "reward_for_advantage_sum": "intrmotiv/reward/advantage_sum",
    "reward_for_advantage_abs_mean": "intrmotiv/reward/advantage_abs_mean",
    "reward_for_advantage_nonzero_frac": "intrmotiv/reward/advantage_nonzero_fraction",
    "reward_for_advantage_min": "intrmotiv/reward/advantage_min",
    "reward_for_advantage_max": "intrmotiv/reward/advantage_max",
    "intrinsic_reward_mean": "intrmotiv/reward/intrinsic_mean",
    "intrinsic_reward_sum": "intrmotiv/reward/intrinsic_sum",
    "intrinsic_reward_nonzero_frac": "intrmotiv/reward/intrinsic_nonzero_fraction",
    "intrinsic_reward_negative_frac": "intrmotiv/reward/intrinsic_negative_fraction",
    "env_reward_mean": "intrmotiv/reward/environment_mean",
    "env_reward_sum": "intrmotiv/reward/environment_sum",
    "env_reward_nonzero_frac": "intrmotiv/reward/environment_nonzero_fraction",
    "dg_density": "intrmotiv/dg/density",
    "dg_multi_activation_rate": "intrmotiv/dg/multi_activation_fraction",
    "dg_silent_unit_frac": "intrmotiv/dg/silent_unit_fraction",
    "dg_unit_duty_cycle_min": "intrmotiv/dg/unit_duty_cycle_min",
    "dg_unit_duty_cycle_mean": "intrmotiv/dg/unit_duty_cycle_mean",
    "dg_unit_duty_cycle_max": "intrmotiv/dg/unit_duty_cycle_max",
    "dg_usage_entropy": "intrmotiv/dg/usage_entropy",
    "dg_learner_active_transition_fraction": "intrmotiv/dg/learner_active_transition_fraction",
    "dg_behavior_dominant_event_fraction": "intrmotiv/dg/behavior_dominant_event_fraction",
    "dg_behavior_multi_onset_event_fraction": "intrmotiv/dg/behavior_multi_onset_event_fraction",
    "dg_behavior_non_dominant_onsets_per_event": "intrmotiv/dg/behavior_non_dominant_onsets_per_event",
    "dg_valid_minibatch_unused_unit_count": "intrmotiv/dg/valid_minibatch_unused_unit_count",
    "dg_valid_minibatch_unused_unit_fraction": "intrmotiv/dg/valid_minibatch_unused_unit_fraction",
    "encoder_penalty_loss": "intrmotiv/encoder/multi_activation_loss",
    "encoder_reward_loss": "intrmotiv/encoder/unused_sequence_loss",
    "batch_reward_loss": "intrmotiv/encoder/batch_usage_loss",
    "extra_decoder_loss": "intrmotiv/decoder/auxiliary_loss",
    "encoder_punishment": "intrmotiv/encoder/feedback_mean",
    "encoder_dominant_event_count": "intrmotiv/encoder/dominant_event_count",
    "encoder_feedback_on_dominant_event_mean": "intrmotiv/encoder/feedback_on_dominant_event_mean",
    "encoder_feedback_abs_on_dominant_event_mean": "intrmotiv/encoder/feedback_abs_on_dominant_event_mean",
    "encoder_credited_row_count": "intrmotiv/encoder/credit/credited_row_count",
    "encoder_arrival_credit_loss": "intrmotiv/encoder/credit/arrival_loss",
    "encoder_source_credit_loss": "intrmotiv/encoder/credit/source_loss",
    "encoder_credit_total": "intrmotiv/encoder/credit/total_events",
    "encoder_credit_matchable": "intrmotiv/encoder/credit/matchable_events",
    "encoder_credit_credited": "intrmotiv/encoder/credit/credited_events",
    "encoder_credit_boundary_dropped": "intrmotiv/encoder/credit/boundary_dropped_events",
    "encoder_credit_alignment_failure": "intrmotiv/encoder/credit/alignment_failures",
    "encoder_credit_invalid_interval": "intrmotiv/encoder/credit/invalid_intervals",
    "encoder_credit_collisions": "intrmotiv/encoder/credit/collisions",
    "encoder_credit_reward_mass": "intrmotiv/encoder/credit/reward_mass",
    "encoder_credit_source_lag_mean": "intrmotiv/encoder/credit/source_lag_mean",
    "encoder_credit_source_lag_max": "intrmotiv/encoder/credit/source_lag_max",
    "encoder_credit_scheduled_count": "intrmotiv/encoder/credit/scheduled_count",
    "encoder_credit_applied_count": "intrmotiv/encoder/credit/applied_count",
    "encoder_credit_scheduled_mass": "intrmotiv/encoder/credit/scheduled_reward_mass",
    "encoder_credit_applied_mass": "intrmotiv/encoder/credit/applied_reward_mass",
    "encoder_credit_replay_match": "intrmotiv/encoder/credit/replay_match",
    "dg_forward_count": "intrmotiv/dg/update_contract/forward_count",
    "dg_running_stats_update_count": "intrmotiv/dg/update_contract/running_stats_update_count",
    "dg_raw_logit_mean_abs": "intrmotiv/dg/normalization/raw_logit_mean_abs",
    "dg_raw_logit_variance_mean": "intrmotiv/dg/normalization/raw_logit_variance_mean",
    "dg_normalized_logit_mean_abs": "intrmotiv/dg/normalization/normalized_logit_mean_abs",
    "dg_normalized_logit_variance_error": "intrmotiv/dg/normalization/normalized_logit_variance_error",
    "dg_ppo_gradient_norm": "intrmotiv/dg/gradient/ppo_norm",
    "dg_encoder_gradient_norm": "intrmotiv/dg/gradient/encoder_norm",
    "dg_gradient_norm_ratio": "intrmotiv/dg/gradient/ppo_encoder_ratio",
    "dg_gradient_cosine": "intrmotiv/dg/gradient/cosine",
    "dg_gradient_row_conflict_fraction": "intrmotiv/dg/gradient/row_conflict_fraction",
    "stale_generation_rejected_count": "intrmotiv/replay/stale_generation_rejected_count",
    "stale_generation_rejected_fraction": "intrmotiv/replay/stale_generation_rejected_fraction",
    "stale_generation_dropped_rollouts_total": "intrmotiv/replay/dropped_rollouts_total",
    "stale_generation_dropped_decisions_total": "intrmotiv/replay/dropped_decisions_total",
    "stale_generation_deferred_updates_total": "intrmotiv/replay/deferred_updates_total",
    "dg_weight_generation": "intrmotiv/dg/update_contract/weight_generation",
    "dg_statistics_generation": "intrmotiv/dg/update_contract/statistics_generation",
    "dg_publication_generation_mismatch": "intrmotiv/dg/update_contract/publication_generation_mismatch",
    "encoder_population_loss": "intrmotiv/encoder/population_loss",
    "encoder_usage_loss": "intrmotiv/encoder/usage_loss",
    "encoder_density_loss": "intrmotiv/encoder/density_loss",
    "encoder_collision_loss": "intrmotiv/encoder/collision_loss",
    "encoder_global_punishment_loss": "intrmotiv/encoder/global_punishment_loss",
    "encoder_row_repulsion_loss": "intrmotiv/encoder/row_repulsion_loss",
    "encoder_ca3_temporal_exclusion_loss": "intrmotiv/encoder/ca3_temporal_exclusion_loss",
    "encoder_path_scatter_loss": "intrmotiv/path/scatter_loss",
    "dg_pre_threshold_mean": "intrmotiv/dg/pre_threshold_mean",
    "dg_pre_threshold_above_fraction": "intrmotiv/dg/pre_threshold_above_fraction",
    "dg_ca3_conflict_fraction": "intrmotiv/dg/ca3_conflict_fraction",
    "dg_ca3_conflicting_activation_fraction": "intrmotiv/dg/ca3_conflicting_activation_fraction",
    "dg_ca3_conflict_activity": "intrmotiv/dg/ca3_conflict_activity",
    "dg_path_scatter_conflict_fraction": "intrmotiv/path/scatter_conflict_fraction",
    "dg_recruitment_committed_fraction": "intrmotiv/dg/recruitment/committed_fraction",
    "dg_recruitment_total": "intrmotiv/dg/recruitment/total",
    "dg_recruitment_repeat_total": "intrmotiv/dg/recruitment/repeat_total",
    "dg_recruitment_tiny_residual_total": "intrmotiv/dg/recruitment/tiny_residual_total",
    "dg_recruitment_candidate_count": "intrmotiv/dg/recruitment/candidate_count",
    "dg_recruitment_silent_endpoint_count": "intrmotiv/dg/recruitment/silent_endpoint_count",
    "dg_recruitment_rollout_count": "intrmotiv/dg/recruitment/rollout_count",
    "dg_recruitment_residual_norm": "intrmotiv/dg/recruitment/residual_norm",
    "dg_recruitment_connected_fraction": "intrmotiv/dg/recruitment/connected_fraction",
    "dg_recruitment_isolated_fraction": "intrmotiv/dg/recruitment/isolated_fraction",
    "dg_recruitment_redundant_pair_count": "intrmotiv/dg/recruitment/redundant_pair_count",
    "dg_recruitment_eligible_vertex_count": "intrmotiv/dg/recruitment/eligible_vertex_count",
    "dg_recruitment_birth_protected_count": "intrmotiv/dg/recruitment/birth_protected_count",
    "dg_recruitment_repeat_assignment_count": "intrmotiv/dg/recruitment/repeat_assignments_per_rollout",
    "dg_recruitment_isolated_assignment_count": "intrmotiv/dg/recruitment/isolated_assignments_per_rollout",
    "dg_recruitment_redundant_assignment_count": "intrmotiv/dg/recruitment/redundant_assignments_per_rollout",
    "dg_recruitment_passive_graph_density": "intrmotiv/dg/recruitment/passive_graph_density",
    "dg_recruitment_passive_update_count": "intrmotiv/dg/recruitment/passive_updates_per_rollout",
    "dg_recruitment_passive_stale_count": "intrmotiv/dg/recruitment/passive_stale_per_rollout",
    "dg_recruitment_passive_over_gap_count": "intrmotiv/dg/recruitment/passive_over_gap_per_rollout",
    "dg_recruitment_attempt_coverage_fraction": "intrmotiv/dg/recruitment/attempt_coverage_fraction",
    "dg_recruitment_fully_tested_count": "intrmotiv/dg/recruitment/fully_tested_count",
    "dg_recruitment_zero_outdegree_count": "intrmotiv/dg/recruitment/zero_outdegree_count",
    "dg_recruitment_untested_zero_outdegree_count": "intrmotiv/dg/recruitment/untested_zero_outdegree_count",
    "dg_recruitment_bad_source_count": "intrmotiv/dg/recruitment/bad_source_count",
    "dg_recruitment_reliable_out_degree_mean": "intrmotiv/dg/recruitment/reliable_out_degree_mean",
    "dg_recruitment_reliable_outgoing_confidence_mean": "intrmotiv/dg/recruitment/reliable_outgoing_confidence_mean",
    "dg_recruitment_predictive_event_count": "intrmotiv/dg/recruitment/predictive_event_count",
    "dg_recruitment_predictive_context_group_count": "intrmotiv/dg/recruitment/predictive_context_group_count",
    "dg_recruitment_predictive_eligible_count": "intrmotiv/dg/recruitment/predictive_eligible_count",
    "dg_recruitment_predictive_reliability_gap": "intrmotiv/dg/recruitment/predictive_reliability_gap",
    "dg_recruitment_bad_source_assignment_count": "intrmotiv/dg/recruitment/bad_source_assignments_per_rollout",
    "dg_recruitment_predictive_assignment_count": "intrmotiv/dg/recruitment/predictive_assignments_per_rollout",
    "dg_recruitment_active_endpoint_count": "intrmotiv/dg/recruitment/active_endpoint_count",
    "dg_recruitment_activity_blocked_count": "intrmotiv/dg/recruitment/activity_blocked_count",
    "dg_recruitment_eligible_victim_endpoint_count": "intrmotiv/dg/recruitment/eligible_victim_endpoint_count",
    "dg_recruitment_residual_pass_count": "intrmotiv/dg/recruitment/residual_pass_count",
    "dg_recruitment_residual_reject_count": "intrmotiv/dg/recruitment/residual_reject_count",
    "dg_recruitment_endpoint_active_unit_count": "intrmotiv/dg/recruitment/endpoint_active_unit_count",
    "dg_recruitment_victim_active_count": "intrmotiv/dg/recruitment/victim_active_count",
    "dg_recruitment_victim_active_fraction": "intrmotiv/dg/recruitment/victim_active_fraction",
    "dg_recruitment_endpoint_active_unit_mean": "intrmotiv/dg/recruitment/endpoint_active_unit_mean",
    "dg_recruitment_replacement_conversion": "intrmotiv/dg/recruitment/replacement_conversion",
    "dg_recruitment_predictive_decayed_attempt_mass": "intrmotiv/dg/recruitment/predictive_decayed_attempt_mass",
    "dg_recruitment_predictive_supported_context_count": "intrmotiv/dg/recruitment/predictive_supported_context_count",
    "dg_recruitment_predictive_invalidation_mass": "intrmotiv/dg/recruitment/predictive_invalidation_mass",
    "dg_recruitment_predictive_context_coverage_fraction": "intrmotiv/dg/recruitment/predictive_context_coverage_fraction",
    "dg_recruitment_eligible_bad_source_endpoint_count": "intrmotiv/dg/recruitment/eligible_bad_source_endpoint_count",
    "dg_recruitment_eligible_redundant_endpoint_count": "intrmotiv/dg/recruitment/eligible_redundant_endpoint_count",
    "dg_recruitment_eligible_predictive_endpoint_count": "intrmotiv/dg/recruitment/eligible_predictive_endpoint_count",
    "dg_recruitment_victim_active_bad_source_count": "intrmotiv/dg/recruitment/victim_active_bad_source_count",
    "dg_recruitment_victim_active_redundant_count": "intrmotiv/dg/recruitment/victim_active_redundant_count",
    "dg_recruitment_victim_active_predictive_count": "intrmotiv/dg/recruitment/victim_active_predictive_count",
    "dg_recruitment_victim_active_bad_source_fraction": "intrmotiv/dg/recruitment/victim_active_bad_source_fraction",
    "dg_recruitment_victim_active_redundant_fraction": "intrmotiv/dg/recruitment/victim_active_redundant_fraction",
    "dg_recruitment_victim_active_predictive_fraction": "intrmotiv/dg/recruitment/victim_active_predictive_fraction",
    "dg_recruitment_goal_adapter_reset_count": "intrmotiv/dg/recruitment/goal_adapter_resets_per_rollout",
    "dg_recruitment_goal_adapter_reset_total": "intrmotiv/dg/recruitment/goal_adapter_reset_total",
    "dg_recruitment_forced_preflight_assignment_count": "intrmotiv/dg/recruitment/forced_preflight_assignments_per_rollout",
    "dg_context_created_fraction": "intrmotiv/dg/context/created_fraction",
    "dg_context_suppressed_fraction": "intrmotiv/dg/context/suppressed_fraction",
    "dg_context_unchanged_fraction": "intrmotiv/dg/context/unchanged_fraction",
    "dg_context_modulation_abs_mean": "intrmotiv/dg/context/modulation_abs_mean",
    "dg_context_modulation_saturation_fraction": "intrmotiv/dg/context/modulation_saturation_fraction",
    "dg_context_adapter_gradient_norm": "intrmotiv/dg/context/adapter_gradient_norm",
    "dg_transition_prediction_loss": "intrmotiv/dg/prediction/loss",
    "dg_transition_prediction_main_loss": "intrmotiv/dg/prediction/main_loss",
    "dg_transition_prediction_control_loss": "intrmotiv/dg/prediction/control_loss",
    "dg_transition_prediction_validation_main_ce": "intrmotiv/dg/prediction/validation_main_ce",
    "dg_transition_prediction_validation_control_ce": "intrmotiv/dg/prediction/validation_control_ce",
    "dg_transition_prediction_validation_state_gain": "intrmotiv/dg/prediction/validation_state_gain",
    "dg_transition_prediction_validation_accuracy": "intrmotiv/dg/prediction/validation_accuracy",
    "dg_transition_prediction_validation_count": "intrmotiv/dg/prediction/validation_count",
    "dg_transition_prediction_scheduled_count": "intrmotiv/dg/prediction/scheduled_count",
    "dg_transition_prediction_applied_count": "intrmotiv/dg/prediction/applied_count",
    "dg_transition_prediction_boundary_drop_count": "intrmotiv/dg/prediction/boundary_drop_count",
    "dg_transition_prediction_replay_match": "intrmotiv/dg/prediction/replay_match",
    "ca3_predictor_loss": "intrmotiv/predictor/loss",
    "ca3_predictor_hit_accuracy": "intrmotiv/predictor/hit_accuracy",
    "ca3_predictor_time_mae": "intrmotiv/predictor/hit_time_mae",
    "ca3_predictor_positive_fraction": "intrmotiv/predictor/positive_fraction",
    "hrl_active_target_frac": "intrmotiv/hrl/active_target_fraction",
    "hrl_active_option_frac": "intrmotiv/hrl/active_option_fraction",
    "hrl_exploration_mode_fraction": "intrmotiv/hrl/exploration/mode_fraction",
    "hrl_source_frac": "intrmotiv/hrl/source_fraction",
    "hrl_target_hit_rate": "intrmotiv/hrl/target_hit_rate",
    "hrl_tctrl_update_rate": "intrmotiv/hrl/tctrl_update_rate",
    "hrl_option_reset_rate": "intrmotiv/hrl/option_reset_rate",
    "hrl_option_timeout_rate": "intrmotiv/hrl/option_timeout_rate",
    "hrl_option_success_fraction": "intrmotiv/hrl/option_success_fraction",
    "hrl_control_correct_count": "intrmotiv/hrl/control/correct_count",
    "hrl_control_wrong_count": "intrmotiv/hrl/control/wrong_count",
    "hrl_control_timeout_count": "intrmotiv/hrl/control/timeout_count",
    "hrl_control_censored_count": "intrmotiv/hrl/control/censored_count",
    "hrl_control_completed_count": "intrmotiv/hrl/control/completed_count",
    "hrl_first_outcome_commanded_numerator": "intrmotiv/hrl/control/commanded_numerator",
    "hrl_first_outcome_commanded_event_count": "intrmotiv/hrl/control/commanded_event_count",
    "hrl_first_outcome_shuffled_numerator": "intrmotiv/hrl/control/shuffled_numerator",
    "hrl_first_outcome_shuffled_event_count": "intrmotiv/hrl/control/shuffled_event_count",
    "hrl_control_correct_elapsed_mean": "intrmotiv/hrl/control/correct_elapsed_mean",
    "hrl_control_wrong_elapsed_mean": "intrmotiv/hrl/control/wrong_elapsed_mean",
    "hrl_control_reward_magnitude_correct_mean": "intrmotiv/hrl/control/correct_reward_magnitude_mean",
    "hrl_control_reward_magnitude_wrong_mean": "intrmotiv/hrl/control/wrong_reward_magnitude_mean",
    "hrl_control_observed_pair_coverage": "intrmotiv/hrl/control/observed_pair_coverage",
    "hrl_control_command_entropy": "intrmotiv/hrl/control/normalized_command_entropy",
    "hrl_control_local_candidate_pair_count": "intrmotiv/hrl/control/local_candidate_pair_count",
    "hrl_control_local_candidate_source_fraction": "intrmotiv/hrl/control/local_candidate_source_fraction",
    "hrl_control_local_candidate_count_mean": "intrmotiv/hrl/control/local_candidate_count_mean",
    "hrl_control_behavior_candidate_count_mean": "intrmotiv/hrl/control/behavior_candidate_count_mean",
    "hrl_learned_deadline_fraction": "intrmotiv/hrl/learned_deadline_fraction",
    "hrl_selected_deadline_mean": "intrmotiv/hrl/selected_deadline_mean",
    "hrl_selected_deadline_positive_mean": "intrmotiv/hrl/selected_deadline_positive_mean",
    "hrl_deadline_selection_fraction": "intrmotiv/hrl/deadline_selection_fraction",
    "hrl_elapsed_on_hit_mean": "intrmotiv/hrl/elapsed_on_hit_mean",
    "hrl_elapsed_on_timeout_mean": "intrmotiv/hrl/elapsed_on_timeout_mean",
    "hrl_exploration_selection_fraction": "intrmotiv/hrl/exploration/selection_fraction",
    "hrl_forced_exploration_fraction": "intrmotiv/hrl/exploration/forced_selection_fraction",
    "hrl_exploration_completion_rate": "intrmotiv/hrl/exploration/completion_rate",
    "hrl_exploration_elapsed_mean": "intrmotiv/hrl/exploration/elapsed_mean",
    "hrl_target_selected_deadline_mean": "intrmotiv/hrl/target_selected_deadline_mean",
    "hrl_exploration_selected_deadline_mean": "intrmotiv/hrl/exploration/selected_deadline_mean",
    "hrl_exploration_reward_mean": "intrmotiv/hrl/exploration/reward_mean",
    "hrl_exploration_reward_nonzero_fraction": "intrmotiv/hrl/exploration/reward_nonzero_fraction",
    "hrl_node_coverage_fraction": "intrmotiv/hrl/node_coverage_fraction",
    "hrl_node_visit_weight_mean": "intrmotiv/hrl/node_visit_weight_mean",
    "hrl_selected_target_visit_mean": "intrmotiv/hrl/selected_target_visit_mean",
    "hrl_known_edge_fraction": "intrmotiv/hrl/known_edge_fraction",
    "hrl_forgotten_edge_fraction": "intrmotiv/hrl/forgotten_edge_fraction",
    "hrl_known_controllability_time_mean": "intrmotiv/hrl/known_controllability_time_mean",
    "hrl_edge_confidence_mean": "intrmotiv/hrl/edge_confidence_mean",
    "hrl_edge_reliability_mean": "intrmotiv/hrl/edge_reliability_mean",
    "hrl_edge_reliability_brier": "intrmotiv/hrl/edge/reliability_brier",
    "hrl_edge_promotions": "intrmotiv/hrl/edge/promotions_per_rollout",
    "hrl_edge_demotions": "intrmotiv/hrl/edge/demotions_per_rollout",
    "hrl_edge_promotion_rate": "intrmotiv/hrl/edge/promotion_rate",
    "hrl_edge_demotion_rate": "intrmotiv/hrl/edge/demotion_rate",
    "hrl_reliable_largest_scc": "intrmotiv/hrl/reliable/largest_scc",
    "hrl_reliable_reachable_pair_fraction": "intrmotiv/hrl/reliable/reachable_pair_fraction",
    "hrl_reliable_outgoing_node_fraction": "intrmotiv/hrl/reliable/outgoing_node_fraction",
    "hrl_reliable_outgoing_node_count": "intrmotiv/hrl/reliable/outgoing_node_count",
    "hrl_reliable_reciprocal_fraction": "intrmotiv/hrl/reliable/reciprocal_fraction",
    "hrl_reliable_top3_incoming_confidence_share": "intrmotiv/hrl/reliable/top3_incoming_confidence_share",
    "hrl_target_hit_lift": "intrmotiv/hrl/target_hit_lift",
    "hrl_target_hit_numerator": "intrmotiv/hrl/target_hit_numerator",
    "hrl_target_hit_event_count": "intrmotiv/hrl/target_hit_event_count",
    "hrl_shuffled_hit_numerator": "intrmotiv/hrl/shuffled_hit_numerator",
    "hrl_shuffled_hit_event_count": "intrmotiv/hrl/shuffled_hit_event_count",
    "hrl_goal_condition_target_valid_fraction": "intrmotiv/hrl/goal_condition/target_valid_fraction",
    "hrl_goal_condition_action_sensitivity": "intrmotiv/hrl/goal_condition/action_sensitivity",
    "hrl_goal_condition_action_probability_tv": "intrmotiv/hrl/goal_condition/action_probability_tv",
    "hrl_goal_condition_value_span": "intrmotiv/hrl/goal_condition/value_span",
    "hrl_goal_decoder_parameter_count": "intrmotiv/hrl/goal_condition/decoder_parameter_count",
    "hrl_goal_condition_film_modulation_norm_mean": "intrmotiv/hrl/goal_condition/film_modulation_norm_mean",
    "hrl_goal_condition_film_modulation_norm_max": "intrmotiv/hrl/goal_condition/film_modulation_norm_max",
    "hrl_behavior_replay_mismatch": "intrmotiv/hrl/behavior_replay_mismatch",
    "hrl_goal_policy_loss": "intrmotiv/hrl/branch/goal_policy_loss",
    "hrl_goal_value_loss": "intrmotiv/hrl/branch/goal_value_loss",
    "hrl_goal_entropy_loss": "intrmotiv/hrl/branch/goal_entropy_loss",
    "hrl_free_policy_loss": "intrmotiv/hrl/branch/free_policy_loss",
    "hrl_free_value_loss": "intrmotiv/hrl/branch/free_value_loss",
    "hrl_free_entropy_loss": "intrmotiv/hrl/branch/free_entropy_loss",
    "empirical_her_loss": "intrmotiv/her/loss",
    "empirical_her_policy_loss": "intrmotiv/her/policy_loss",
    "empirical_her_value_loss": "intrmotiv/her/value_loss",
    "empirical_her_behavior_ratio": "intrmotiv/her/behavior_logprob_ratio",
    "empirical_her_clip_fraction": "intrmotiv/her/clip_fraction",
    "empirical_her_valid_fraction": "intrmotiv/her/valid_fraction",
    "empirical_her_accepted_segments": "intrmotiv/her/accepted_segments_per_rollout",
    "empirical_her_skipped_no_endpoint": "intrmotiv/her/skipped_no_endpoint_per_rollout",
    "empirical_her_skipped_same_source": "intrmotiv/her/skipped_same_source_per_rollout",
    "empirical_her_segment_length": "intrmotiv/her/segment_length",
    "empirical_her_positive_fraction": "intrmotiv/her/positive_fraction",
    "empirical_her_terminal_reward": "intrmotiv/her/terminal_reward",
    "hrl_passive_updates": "intrmotiv/hrl/passive/updates_per_rollout",
    "hrl_passive_known_edge_fraction": "intrmotiv/hrl/passive/known_edge_fraction",
    "hrl_passive_candidate_edge_fraction": "intrmotiv/hrl/passive/candidate_edge_fraction",
    "hrl_passive_time_mean": "intrmotiv/hrl/passive/traversal_time_mean",
    "hrl_passive_path_length_mean": "intrmotiv/hrl/passive/path_length_mean",
    "hrl_passive_reject_nonexclusive_rate": "intrmotiv/hrl/passive/reject_nonexclusive_rate",
    "hrl_passive_reject_time_rate": "intrmotiv/hrl/passive/reject_time_rate",
    "hrl_passive_reject_path_rate": "intrmotiv/hrl/passive/reject_path_rate",
    "hrl_passive_reject_motion_rate": "intrmotiv/hrl/passive/reject_motion_rate",
    "hrl_frontier_score_mean": "intrmotiv/hrl/frontier/score_mean",
    "hrl_frontier_selection_rate": "intrmotiv/hrl/frontier/selection_rate",
    "hrl_frontier_attempts": "intrmotiv/hrl/frontier/attempts_per_rollout",
    "hrl_frontier_discoveries": "intrmotiv/hrl/frontier/discoveries_per_rollout",
    "hrl_frontier_yield": "intrmotiv/hrl/frontier/yield",
    "hrl_frontier_reached_fraction": "intrmotiv/hrl/frontier/reached_fraction",
    "hrl_planning_route_available_rate": "intrmotiv/hrl/planning/route_available_rate",
    "hrl_planning_hop_count_mean": "intrmotiv/hrl/planning/hop_count_mean",
    "hrl_planning_waypoint_success_rate": "intrmotiv/hrl/planning/waypoint_success_rate",
    "hrl_planning_replan_rate": "intrmotiv/hrl/planning/replan_rate",
    "hrl_planning_final_frontier_reach_rate": "intrmotiv/hrl/planning/final_frontier_reach_rate",
    "hrl_validation_queued_edges": "intrmotiv/hrl/validation/queued_edges",
    "hrl_validation_return_success_rate": "intrmotiv/hrl/validation/return_success_rate",
    "hrl_validation_success_rate": "intrmotiv/hrl/validation/success_rate",
    "hrl_validation_timeout_rate": "intrmotiv/hrl/validation/timeout_rate",
    "hrl_mode_free_fraction": "intrmotiv/hrl/mode/free_fraction",
    "hrl_mode_navigate_fraction": "intrmotiv/hrl/mode/navigate_fraction",
    "hrl_mode_goal_fraction": "intrmotiv/hrl/mode/goal_fraction",
    "hrl_mode_probe_fraction": "intrmotiv/hrl/mode/probe_fraction",
    "hrl_edge_candidate_rate": "intrmotiv/hrl/edge/candidate_fraction",
    "hrl_edge_probe_rate": "intrmotiv/hrl/edge/probe_fraction",
    "hrl_edge_probe_successes": "intrmotiv/hrl/edge/probe_successes_per_rollout",
    "hrl_edge_probe_timeouts": "intrmotiv/hrl/edge/probe_timeouts_per_rollout",
    "hrl_edge_probe_success_rate": "intrmotiv/hrl/edge/probe_success_rate",
    "hrl_edge_probe_timeout_rate": "intrmotiv/hrl/edge/probe_timeout_rate",
    "hrl_goal_target_hit_rate": "intrmotiv/hrl/by_mode/goal_target_hit_rate",
    "hrl_goal_time_to_hit": "intrmotiv/hrl/by_mode/goal_time_to_hit",
    "hrl_goal_path_length": "intrmotiv/hrl/by_mode/goal_path_length",
    "hrl_goal_straightness": "intrmotiv/hrl/by_mode/goal_straightness",
    "hrl_goal_loop_fraction": "intrmotiv/hrl/by_mode/goal_loop_fraction",
    "hrl_free_target_hit_rate": "intrmotiv/hrl/by_mode/free_target_hit_rate",
    "hrl_free_time_to_hit": "intrmotiv/hrl/by_mode/free_time_to_hit",
    "hrl_free_path_length": "intrmotiv/hrl/by_mode/free_path_length",
    "hrl_free_straightness": "intrmotiv/hrl/by_mode/free_straightness",
    "hrl_free_loop_fraction": "intrmotiv/hrl/by_mode/free_loop_fraction",
    "hrl_probe_target_hit_rate": "intrmotiv/hrl/by_mode/probe_target_hit_rate",
    "hrl_probe_time_to_hit": "intrmotiv/hrl/by_mode/probe_time_to_hit",
    "hrl_probe_path_length": "intrmotiv/hrl/by_mode/probe_path_length",
    "hrl_probe_straightness": "intrmotiv/hrl/by_mode/probe_straightness",
    "hrl_probe_loop_fraction": "intrmotiv/hrl/by_mode/probe_loop_fraction",
    "path_length_mean": "intrmotiv/path/path_length_mean",
    "path_displacement_mean": "intrmotiv/path/displacement_mean",
    "path_straightness_mean": "intrmotiv/path/straightness_mean",
    "geometry_se2_stress": "intrmotiv/geometry/se2_stress",
    "geometry_valid_landmark_fraction": "intrmotiv/geometry/valid_landmark_fraction",
    "geometry_proposed_edge_fraction": "intrmotiv/geometry/proposed_edge_fraction",
    "online_spatial_place_valid_sample_count": "intrmotiv/online/place_field/valid_sample_count",
    "online_spatial_place_in_bounds_fraction": "intrmotiv/online/place_field/in_bounds_fraction",
    "online_spatial_place_visited_cell_fraction": "intrmotiv/online/place_field/visited_cell_fraction",
    "online_spatial_place_active_unit_fraction": "intrmotiv/online/place_field/active_unit_fraction",
    "online_spatial_place_silent_unit_fraction": "intrmotiv/online/place_field/silent_unit_fraction",
    "online_spatial_place_active_unit_mean_spatial_information": "intrmotiv/online/place_field/active_unit_mean_spatial_information",
    "online_spatial_place_active_only_map_cosine": "intrmotiv/online/place_field/active_only_map_cosine",
    "online_spatial_place_unique_active_peak_bins": "intrmotiv/online/place_field/unique_active_peak_bins",
    "online_spatial_place_mono_field_unit_fraction": "intrmotiv/online/place_field/mono_field_unit_fraction",
    "online_spatial_place_mean_primary_secondary_peak_distance": "intrmotiv/online/place_field/mean_primary_secondary_peak_distance",
    "online_spatial_place_median_dominant_peak_nearest_neighbor_distance": "intrmotiv/online/place_field/median_dominant_peak_nearest_neighbor_distance",
    "online_spatial_trajectory_mean_physical_step_distance": "intrmotiv/online/trajectory/mean_physical_step_distance",
    "online_spatial_trajectory_stationary_step_fraction": "intrmotiv/online/trajectory/stationary_step_fraction",
    "online_spatial_trajectory_path_efficiency": "intrmotiv/online/trajectory/path_efficiency",
    "online_spatial_trajectory_mean_absolute_circular_yaw_change": "intrmotiv/online/trajectory/mean_absolute_circular_yaw_change",
    "online_spatial_scalar_target_env_steps": "intrmotiv/online/window/target_env_steps",
    "online_spatial_graph_reliable_global_efficiency": "intrmotiv/hrl/summary/reliable_global_efficiency",
    "online_spatial_graph_grounded_controllability": "intrmotiv/hrl/summary/grounded_controllability",
}


def _append_policy_stat(runner, key, policy_id, value):
    if key not in runner.policy_avg_stats:
        runner.policy_avg_stats[key] = [deque(maxlen=1) for _ in range(runner.cfg.num_policies)]
    runner.policy_avg_stats[key][policy_id].append(float(value))


def write_intrmotiv_summaries(runner, msg, policy_id):
    """Write IntrMotiv metrics and hide their duplicate train/ series."""
    train_stats = msg[TRAIN_STATS]
    env_steps = msg.get(LEARNER_ENV_STEPS, runner.env_steps[policy_id])
    writer = runner.writers[policy_id]

    cfg = getattr(runner, "cfg", None)
    required = ("dg_silent_unit_frac", "hrl_active_target_frac", "intrinsic_reward_negative_frac")
    if getattr(cfg, "with_pbt", False) and all(key in train_stats for key in required):
        coverage_keys = [key for key in runner.policy_avg_stats if key.endswith("coverage_auc")]
        if coverage_keys and runner.policy_avg_stats[coverage_keys[0]][policy_id]:
            valid = (
                train_stats["dg_silent_unit_frac"] <= cfg.hrl_pbt_max_silent_fraction
                and train_stats["hrl_active_target_frac"] > 0.5
                and train_stats["intrinsic_reward_negative_frac"] == 0
            )
            coverage = float(runner.policy_avg_stats[coverage_keys[0]][policy_id][-1])
            objective = coverage if valid else 0.0
            _append_policy_stat(runner, "intrmotiv_hrl_validity", policy_id, float(valid))
            _append_policy_stat(runner, "intrmotiv_pbt_objective", policy_id, objective)
            writer.add_scalar("intrmotiv/pbt/hrl_validity", float(valid), env_steps)
            writer.add_scalar("intrmotiv/pbt/objective", objective, env_steps)

    for source_key, summary_tag in INTRMOTIV_SUMMARY_TAGS.items():
        if source_key in train_stats:
            writer.add_scalar(summary_tag, train_stats[source_key], env_steps)

    for source_key in INTRMOTIV_SUMMARY_TAGS:
        train_stats.pop(source_key, None)


# Compatibility for existing scripts that imported the old callback name.
write_reward_summaries = write_intrmotiv_summaries
